language: go

go:
 - 1.4

install:
 - go get github.com/spf13/cobra
 - go get github.com/spf13/viper
 - go get github.com/BurntSushi/toml
 - go get github.com/spf13/pflag

script: go test ./lib/... ./cmd/...